# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: shivammathur/setup-php@v2
  inputs:
    php-version: '8.4'
    extensions: mbstring, intl, pdo_mysql

- script: |
    composer install
    ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php ./tests/quotetest.php
  displayName: 'Run composer'
