# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  phpVersion: '8.5' # Define target version

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: |
    composer install
    ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php ./tests/quotetest.php
  displayName: 'Run composer'
